spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pms?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,logback
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
  jmx:
    default-domain: agentservice
  mvc:
    date-format: yyyy-MM-dd
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss 
server:
  servlet:
    context-path: /pockethome
endpoints: 
  jmx:
    domain: agentservice
    unique-names: true
druid: 
  loginUsername: druidadmin
  loginPassword: druidadmin
weichat: 
  appid: wx2ec2c331d6af829a
  appsecret: 6f062ee6567537c0e7e0705733b8580d
  authaccesstoken: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=SECRET&code=CODE&grant_type=authorization_code
  accesstoken: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
  messagetemplate: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=
  ordertemplateid: rTxoIxu4UKgJrW2P377X9JkWyMSvhzqSB1_hMvJdRpw
